### ISSUE TITLE
JBoss EAP needs JTA autoconfiguration excluded

### ISSUE THREAD

**Issue by scrain** [grails-profiles/web-jboss7#1]
We ran into an issue with a Grails 3.1.14 application with JBoss EAP that required us to exclude JTA autoconfiguration from the Grails `Application` class as Graeme previously described for Wildfly [here](http://grails.io/post/142674392718/deploying-grails-3-to-wildfly-10).  The issue only manifested itself in our secured REST API calls.  Our application is triggering a call to the database during Spring security's authentication work and it was during these that the JTA autoconfiguration was causing an issue.
```
import org.springframework.boot.autoconfigure.transaction.jta.*
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import grails.boot.GrailsApp
import grails.boot.config.GrailsAutoConfiguration
@EnableAutoConfiguration(exclude=[JtaAutoConfiguration])
class Application extends GrailsAutoConfiguration {
    static void main(String[] args) {
        GrailsApp.run(Application, args)
    }
}
```

**Comment by scrain** [comment]
Just further clarification on this issue, but specifically this was JBoss 6.4 EAP.

**Comment by graemerocher** [comment]
Thanks for the report I will do another RC with this change in it

**Comment by graemerocher** [comment]
Fixed by https://github.com/grails-profiles/web-jboss7/commit/4d3b753029fbc211cb9be9574648df685f3229b9

**Comment by virtualkit** [comment]
Hi,

i followed this [steps](http://grails.io/post/142674392718/deploying-grails-3-to-wildfly-10) and created the Application class under grails-app/init/Application.groovy but when execute **grails war**, it throws this error

```
grails-app/init/Application.groovy: 6: Only classes and closures can be used for attribute 'exclude' in @org.springframework.boot.autoconfigure.EnableAutoConfiguration
 @ line 6, column 35.
   @EnableAutoConfiguration(exclude=[JtaAutoConfiguration])
```

I am using jdk1.8, grails 3.0.8.

Thanks,
kit.
